"""alter table person add column state

Revision ID: e79d21c303da
Revises: d8c97f528144
Create Date: 2022-09-12 22:39:24.889177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79d21c303da'
down_revision = 'd8c97f528144'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('state', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'state')
    # ### end Alembic commands ###
